### ISSUE TITLE
Forking and license

### ISSUE THREAD

**Issue by winternet-studio** [HenryVolkmer/yii2-wordpress-glue#4]
Tried this but couldn't get it working as is. Are you okay with me forking it and putting an MIT license on it?

**Comment by winternet-studio** [comment]
Ahh, saw the MIT mention in the composer file :)

**Comment by HenryVolkmer** [comment]
feel free!
I had no time to complete this thing; but its operative in a "customer-suited" Version.

**Comment by winternet-studio** [comment]
Thanks, I'll see how far I get :)

**Comment by winternet-studio** [comment]
I have been going through the code but I'm struggling to understand what the Tabs widget is doing at edit_form_after_title and what the ModelRegister is... I don't see anything different in the admin UI as is... Also what is the Template model for? Do you might explaining what these are for?
